### ISSUE TITLE
Integrate curvefit function into local estimator

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#1244]
### What would you like to be added?

Update local estimator to support other curvefit function introduced in kepler-model-server

### Why is this needed?

To expand choice of modeling on local estimator

### TODO
- [ ] update kepler-model-server to new logarithm fitting function 
- [ ] update trained SPECPower to kepler-model-db 
- [ ] update kepler code
